### ISSUE TITLE
Convert sanitized HTML into Markdown

### ISSUE THREAD

**Issue by alicerunsonfedora** [hyperspacedev/labs-swiftui#19]
- [x] I know that I'm requesting a feature for Codename Starlight (SwiftUI) and not for Hyperspace Desktop (JS).

Previously, we aimed to try rendering the sanitized HTML content from a status with #6. However, with the new improvements in SwiftUI, we should be able to convert this into Markdown for SwiftUI to render on its own.

**Tasks**
- [ ] Convert emojicodes (`:thumbsup:`) into their corresponding emojis (👍🏻)
- [ ] Parse anchor tags (`<a>`) into proper Markdown links that the deep linker can use
- [x] Strip away basic HTML attributes and replace them with Markdown equivalents (ex.: `<b>` to `**`, `<I>` to `_`)
- [ ] Add cards for extra information that a status provides (see also: #11)

Note: This issue supersedes #6.
