### ISSUE TITLE
Add notifications to notifications page

### ISSUE THREAD

**Issue by alicerunsonfedora** [hyperspacedev/labs-swiftui#20]
The notifications page should feel similar to what's offered in the web interface.

**Tasks**

- [ ] Render all cells for notifications.
- [ ] Filter for mentions.
- [ ] Add option to clear an individual notification and/or the entire notification list.
- [ ] Add options to respond with swipe gestures.
